//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmpDocuments = new HashSet<EmpDocument>();
        }
    
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string Designation { get; set; }
        public int PhoneNo { get; set; }
        public string Email { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> ZoneId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string Technology { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpDocument> EmpDocuments { get; set; }
        public virtual Region Region { get; set; }
        public virtual Zone Zone { get; set; }
    }
}
