//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone_copy
    {
        public int ZoneId { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> RegionId { get; set; }
    }
}
